// <auto-generated />
using System;
using EmergencyAppAws.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyAppAws.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyAppAws.API.Models.EmergencyApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmergencyApplications", (string)null);
                });

            modelBuilder.Entity("EmergencyAppAws.API.Models.EmergencyApplication", b =>
                {
                    b.OwnsOne("EmergencyAppAws.API.Models.BankInfo", "Bank", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BranchNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("InstitutionNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("BankInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("HomeAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("PhoneNumber1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber2")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("ContactInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.FamilyInfo", "Family", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<int>("ChildrenCount")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("MaritalStatus")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("FamilyInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.FinancialInfo", "Financial", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Assets")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Credit")
                                .HasColumnType("numeric");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<decimal>("MonthlyIncome")
                                .HasColumnType("numeric");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("FinancialInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.HousingInfo", "Housing", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<string>("CurrentSituation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<decimal>("MonthlyCost")
                                .HasColumnType("numeric");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("HousingInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.PersonalInfo", "Personal", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("HealthCardNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsStudent")
                                .HasColumnType("boolean");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SIN")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SexAtBirth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StatusInCanada")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("PersonalInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.ReasonForApplication", "Reason", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<bool>("CanGetOtherMoney")
                                .HasColumnType("boolean");

                            b1.Property<string>("DurationNeeded")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("HasEnoughMoney")
                                .HasColumnType("boolean");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("OtherInfo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Situation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("Reasons", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.OwnsOne("EmergencyAppAws.API.Models.WorkInfo", "Work", b1 =>
                        {
                            b1.Property<int>("EmergencyApplicationId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("JobSituation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmergencyApplicationId");

                            b1.ToTable("WorkInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmergencyApplicationId");
                        });

                    b.Navigation("Bank")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Family")
                        .IsRequired();

                    b.Navigation("Financial")
                        .IsRequired();

                    b.Navigation("Housing")
                        .IsRequired();

                    b.Navigation("Personal")
                        .IsRequired();

                    b.Navigation("Reason")
                        .IsRequired();

                    b.Navigation("Work")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
